#正在启动的环境
spring:
  profiles:
    active:
      - dev

---
#开发环境配置
spring:
  profiles: dev
  application:
    name: springCloud-config-config-dev

---
#测试环境配置
spring:
  profiles:
  application:
    name: springCloud-config-config-test
#请保存为UTF-8编码格式

  